# Information for Alpha Configuration Server
[server]
    # Server hostname
    host = "localhost"

    # Server port
    port = 52890

    # Number of seconds between polling for scheduled/canceled probes
    probe_poll_seconds = 30

# Configuration for this prober
[prober]
    # Number of threads in the probing threadpool
    probe_threads = 4

    # Minimum priority of probes this prober will execute
    probe_priority = 0

    # Writer configuration for probe results
    writer = "FileWriter"
