# Hostname of machine this is running on
prober_hostname = "test.netsec.colostate.edu"

# Number of threads in the probing threadpool
probe_threads = 24

# Information for Configuration Server
[server]
    # Server hostname
    host = "localhost"

    # Server port
    port = 52890

    # Number of seconds between polling for scheduled/canceled probes
    probe_poll_seconds = 30
