# Number of domain buckets
bucket_count = 1000

# Writer configuration for probe results
[writer]
    # Writer type
    # FileWriter: Writes protobuf to file
    #   directory: Directory to write protobuf files
    #   max_filesize: Maximum filesize of protobuf files
    # PrintWriter: Prints protobuf to stdout
    type = "FileWriter"

    # Directory to write probe result protobuf files to
    directory = "/tmp"

    # Maximum filesize of probe result files (default: 10MB)
    max_filesize = 10485760
